name: Feature request
description: Suggest an idea for netcup-kube
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem are you trying to solve?
  - type: textarea
    attributes:
      label: Proposal
      description: Describe the solution you'd like
  - type: textarea
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered
  - type: checkboxes
    attributes:
      label: Impact
      options:
        - label: Backward compatible
        - label: Requires docs update