#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck disable=SC1091
source "${SCRIPTS_DIR}/lib/common.sh"

apply_template() {
  local template_path="$1"
  [[ -f "${template_path}" ]] || die "Missing manifest template: ${template_path}"

  # Keep this dependency-free: replace well-known placeholders with sed.
  # Use a delimiter that is unlikely to appear in values.
  sed \
    -e "s|__NAMESPACE__|${NAMESPACE}|g" \
    -e "s|__IMAGE_VERSION_REDISINSIGHT__|${IMAGE_VERSION_REDISINSIGHT}|g" \
    -e "s|__HOST__|${HOST}|g" \
    -e "s|__REDIS_HOST__|${REDIS_HOST}|g" \
    -e "s|__REDIS_PORT__|${REDIS_PORT}|g" \
    -e "s|__REDIS_ALIAS__|${REDIS_ALIAS}|g" \
    "${template_path}" | k apply -f -
}

usage() {
  cat << 'EOF'
Install RedisInsight on the cluster using Helm (Redis GUI).

Usage:
  netcup-kube-install redisinsight [--namespace platform] [--host redis.example.com] [--with-redis]

Options:
  --namespace <name>   Namespace to install into (default: platform).
  --host <fqdn>        Create a Traefik Ingress for this host (entrypoint: web).
  --with-redis         Install Redis in the same namespace first (via the existing `redis` recipe) if missing.
  --redis-storage <s>  Redis PVC size (default: recipes.conf DEFAULT_STORAGE_REDIS).
  --redis-password <p> Redis password (default: auto-generated by the Redis recipe).
  -h, --help           Show this help.

Environment:
  KUBECONFIG           Kubeconfig to use. If not set, defaults to /etc/rancher/k3s/k3s.yaml (on the node).

Notes:
  - This installs RedisInsight from the official Helm chart.
  - RedisInsight provides a web GUI to manage Redis instances.
  - If you pass --host, the domain will be auto-added to Caddy edge-http domains (if on server).
  - You can connect to Redis instances in the cluster via their service names.
  - If you pass --with-redis, RedisInsight will be preconfigured to connect to the in-cluster service:
    redis-master.<namespace>.svc.cluster.local:6379
EOF
}

NAMESPACE="${NAMESPACE:-${NAMESPACE_PLATFORM}}"
HOST=""
WITH_REDIS="false"
REDIS_STORAGE="${DEFAULT_STORAGE_REDIS}"
REDIS_PASSWORD=""
REDIS_HOST=""
REDIS_PORT="6379"
REDIS_ALIAS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --namespace)
      shift
      NAMESPACE="${1:-}"
      ;;
    --namespace=*)
      NAMESPACE="${1#*=}"
      ;;
    --host)
      shift
      HOST="${1:-}"
      ;;
    --host=*)
      HOST="${1#*=}"
      ;;
    --with-redis)
      WITH_REDIS="true"
      ;;
    --redis-storage)
      shift
      REDIS_STORAGE="${1:-}"
      ;;
    --redis-storage=*)
      REDIS_STORAGE="${1#*=}"
      ;;
    --redis-password)
      shift
      REDIS_PASSWORD="${1:-}"
      ;;
    --redis-password=*)
      REDIS_PASSWORD="${1#*=}"
      ;;
    -h | --help | help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
  shift || true
done

[[ -n "${NAMESPACE}" ]] || die "Namespace is required"

REDIS_HOST="redis-master.${NAMESPACE}.svc.cluster.local"
REDIS_ALIAS="redis-${NAMESPACE}"

log "Installing RedisInsight into namespace: ${NAMESPACE}"

# Ensure namespace exists
log "Ensuring namespace exists"
k create namespace "${NAMESPACE}" --dry-run=client -o yaml | k apply -f -

# Ensure RedisInsight has a stable encryption key for storing sensitive data (DB passwords) in /data.
#
# Without this, some environments fail to initialize keychain-based encryption (keytar/libsecret),
# which can prevent storing configured connections.
if ! k -n "${NAMESPACE}" get secret redisinsight-encryption > /dev/null 2>&1; then
  log "Creating RedisInsight encryption secret (redisinsight-encryption)"
  enc_key="$(head -c 32 /dev/urandom | base64 | tr -d '\n')"
  k -n "${NAMESPACE}" create secret generic redisinsight-encryption --from-literal=encryption-key="${enc_key}"
else
  log "RedisInsight encryption secret already present (redisinsight-encryption)."
fi

# Optional: ensure Redis exists first (so RedisInsight has something to connect to out-of-the-box).
if [[ "${WITH_REDIS}" == "true" ]]; then
  if k -n "${NAMESPACE}" get svc redis-master > /dev/null 2>&1; then
    log "Redis already present (svc/redis-master). Skipping Redis install."
  else
    log "Redis not found (svc/redis-master). Installing Redis first (Bitnami chart) via redis recipe."
    redis_installer="${SCRIPTS_DIR}/recipes/redis/install.sh"
    [[ -x "${redis_installer}" ]] || chmod +x "${redis_installer}"
    redis_args=(--namespace "${NAMESPACE}")
    if [[ -n "${REDIS_STORAGE}" ]]; then
      redis_args+=(--storage "${REDIS_STORAGE}")
    fi
    if [[ -n "${REDIS_PASSWORD}" ]]; then
      redis_args+=(--password "${REDIS_PASSWORD}")
    fi
    "${redis_installer}" "${redis_args[@]}"
  fi
fi

# Deploy RedisInsight using manifests
log "Deploying RedisInsight"
apply_template "${SCRIPT_DIR}/pvc.yaml"
if [[ "${WITH_REDIS}" == "true" ]]; then
  apply_template "${SCRIPT_DIR}/deployment.with-redis.yaml"
else
  apply_template "${SCRIPT_DIR}/deployment.yaml"
fi
apply_template "${SCRIPT_DIR}/service.yaml"

log "Waiting for RedisInsight to be ready"
k wait --for=condition=available --timeout=300s deployment/redisinsight -n "${NAMESPACE}"

log "RedisInsight installed successfully!"
echo

seed_redisinsight_connection() {
  local host="$1"
  local port="$2"
  local name="$3"
  local username="$4"

  command -v curl > /dev/null 2>&1 || {
    log "WARN: curl not found; cannot auto-seed RedisInsight connection."
    return 0
  }

  local password
  password="$(k -n "${NAMESPACE}" get secret redis -o jsonpath='{.data.redis-password}' | base64 -d 2> /dev/null || true)"
  [[ -n "${password}" ]] || {
    log "WARN: could not read Redis password from Secret/redis; cannot auto-seed RedisInsight connection."
    return 0
  }

  # Use a short-lived port-forward so we can call the RedisInsight API.
  # The service exposes port 80 -> container 5540.
  local pf_port="18001"
  local pf_log="/tmp/netcup-kube-redisinsight-portforward.$$.log"
  local pf_pid=""

  k -n "${NAMESPACE}" port-forward svc/redisinsight "${pf_port}:80" > "${pf_log}" 2>&1 &
  pf_pid="$!"
  trap 'kill "${pf_pid}" 2>/dev/null || true; wait "${pf_pid}" 2>/dev/null || true; rm -f "${pf_log}"' RETURN

  # Wait for port-forward to be ready
  for _ in {1..30}; do
    if curl -fsS "http://127.0.0.1:${pf_port}/api/databases" > /dev/null 2>&1; then
      break
    fi
    sleep 0.2
  done

  # If the DB already exists, do nothing.
  if curl -fsS "http://127.0.0.1:${pf_port}/api/databases" | grep -q "\"name\":\"${name}\""; then
    log "RedisInsight already has database '${name}'."
    return 0
  fi

  log "Seeding RedisInsight connection '${name}' -> ${host}:${port}"
  curl -fsS -X POST "http://127.0.0.1:${pf_port}/api/databases" \
    -H 'Content-Type: application/json' \
    -d "{\"name\":\"${name}\",\"host\":\"${host}\",\"port\":${port},\"username\":\"${username}\",\"password\":\"${password}\"}" \
    > /dev/null
}

if [[ "${WITH_REDIS}" == "true" ]]; then
  # Make Redis show up by default inside RedisInsight.
  # Some RedisInsight versions do not reliably auto-add DBs from RI_REDIS_* env vars in Kubernetes,
  # so we seed the connection via the local API once.
  seed_redisinsight_connection "${REDIS_HOST}" "${REDIS_PORT}" "${REDIS_ALIAS}" "default" || true
fi

if [[ -n "${HOST}" ]]; then
  log "Creating/Updating Traefik ingress for ${HOST}"
  apply_template "${SCRIPT_DIR}/ingress.yaml"

  log "NOTE: Ensure ${HOST} is in your edge-http domains before accessing the UI."
  if [[ -f "/etc/caddy/Caddyfile" ]]; then
    # We are on the server; append domain using the dedicated subcommand (safer than rewriting the full list).
    if command -v "${SCRIPTS_DIR}/main.sh" > /dev/null 2>&1; then
      log "  Appending ${HOST} to Caddy edge-http domains (if needed)."
      "${SCRIPTS_DIR}/main.sh" dns --type edge-http --add-domains "${HOST}"
    else
      echo "  Run: sudo ./bin/netcup-kube dns --type edge-http --add-domains \"${HOST}\""
    fi
  else
    echo "  From your laptop:"
    echo "    bin/netcup-kube-remote run dns --show --type edge-http --format csv  # to see current list"
    echo "    bin/netcup-kube-remote run dns --type edge-http --add-domains \"${HOST}\""
  fi
fi

echo
echo "RedisInsight UI:"
if [[ -n "${HOST}" ]]; then
  echo "  URL: https://${HOST}/"
else
  echo "  Port-forward: kubectl port-forward -n ${NAMESPACE} svc/redisinsight 8001:80"
  echo "  Then open: http://localhost:8001"
fi
echo
echo "To connect to Redis instances in the cluster:"
echo "  - Host: redis-master.${NAMESPACE}.svc.cluster.local (or your Redis service name)"
echo "  - Port: 6379"
echo "  - Auth: Get password from: kubectl get secret -n ${NAMESPACE} redis -o jsonpath='{.data.redis-password}' | base64 -d"
