#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck disable=SC1091
source "${SCRIPTS_DIR}/lib/common.sh"

apply_template() {
  local template_path="$1"
  [[ -f "${template_path}" ]] || die "Missing manifest template: ${template_path}"

  # Keep this dependency-free: replace well-known placeholders with sed.
  # Use a delimiter that is unlikely to appear in values.
  sed \
    -e "s|__NAMESPACE__|${NAMESPACE}|g" \
    -e "s|__IMAGE_VERSION_REDISINSIGHT__|${IMAGE_VERSION_REDISINSIGHT}|g" \
    -e "s|__HOST__|${HOST}|g" \
    "${template_path}" | k apply -f -
}

usage() {
  cat << 'EOF'
Install RedisInsight on the cluster using Helm (Redis GUI).

Usage:
  netcup-kube-install redisinsight [--namespace platform] [--host redis.example.com] [--with-redis]

Options:
  --namespace <name>   Namespace to install into (default: platform).
  --host <fqdn>        Create a Traefik Ingress for this host (entrypoint: web).
  --with-redis         Install Redis in the same namespace first (via the existing `redis` recipe) if missing.
  --redis-storage <s>  Redis PVC size (default: recipes.conf DEFAULT_STORAGE_REDIS).
  --redis-password <p> Redis password (default: auto-generated by the Redis recipe).
  -h, --help           Show this help.

Environment:
  KUBECONFIG           Kubeconfig to use. If not set, defaults to /etc/rancher/k3s/k3s.yaml (on the node).

Notes:
  - This installs RedisInsight from the official Helm chart.
  - RedisInsight provides a web GUI to manage Redis instances.
  - If you pass --host, the domain will be auto-added to Caddy edge-http domains (if on server).
  - You can connect to Redis instances in the cluster via their service names.
EOF
}

NAMESPACE="${NAMESPACE:-${NAMESPACE_PLATFORM}}"
HOST=""
WITH_REDIS="false"
REDIS_STORAGE="${DEFAULT_STORAGE_REDIS}"
REDIS_PASSWORD=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --namespace)
      shift
      NAMESPACE="${1:-}"
      ;;
    --namespace=*)
      NAMESPACE="${1#*=}"
      ;;
    --host)
      shift
      HOST="${1:-}"
      ;;
    --host=*)
      HOST="${1#*=}"
      ;;
    --with-redis)
      WITH_REDIS="true"
      ;;
    --redis-storage)
      shift
      REDIS_STORAGE="${1:-}"
      ;;
    --redis-storage=*)
      REDIS_STORAGE="${1#*=}"
      ;;
    --redis-password)
      shift
      REDIS_PASSWORD="${1:-}"
      ;;
    --redis-password=*)
      REDIS_PASSWORD="${1#*=}"
      ;;
    -h | --help | help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
  shift || true
done

[[ -n "${NAMESPACE}" ]] || die "Namespace is required"

log "Installing RedisInsight into namespace: ${NAMESPACE}"

# Ensure namespace exists
log "Ensuring namespace exists"
k create namespace "${NAMESPACE}" --dry-run=client -o yaml | k apply -f -

# Optional: ensure Redis exists first (so RedisInsight has something to connect to out-of-the-box).
if [[ "${WITH_REDIS}" == "true" ]]; then
  if k -n "${NAMESPACE}" get svc redis-master > /dev/null 2>&1; then
    log "Redis already present (svc/redis-master). Skipping Redis install."
  else
    log "Redis not found (svc/redis-master). Installing Redis first (Bitnami chart) via redis recipe."
    redis_installer="${SCRIPTS_DIR}/recipes/redis/install.sh"
    [[ -x "${redis_installer}" ]] || chmod +x "${redis_installer}"
    redis_args=(--namespace "${NAMESPACE}")
    if [[ -n "${REDIS_STORAGE}" ]]; then
      redis_args+=(--storage "${REDIS_STORAGE}")
    fi
    if [[ -n "${REDIS_PASSWORD}" ]]; then
      redis_args+=(--password "${REDIS_PASSWORD}")
    fi
    "${redis_installer}" "${redis_args[@]}"
  fi
fi

# Deploy RedisInsight using manifests
log "Deploying RedisInsight"
apply_template "${SCRIPT_DIR}/pvc.yaml"
apply_template "${SCRIPT_DIR}/deployment.yaml"
apply_template "${SCRIPT_DIR}/service.yaml"

log "Waiting for RedisInsight to be ready"
k wait --for=condition=available --timeout=300s deployment/redisinsight -n "${NAMESPACE}"

log "RedisInsight installed successfully!"
echo

if [[ -n "${HOST}" ]]; then
  log "Creating/Updating Traefik ingress for ${HOST}"
  apply_template "${SCRIPT_DIR}/ingress.yaml"

  log "NOTE: Ensure ${HOST} is in your edge-http domains before accessing the UI."
  if [[ -f "/etc/caddy/Caddyfile" ]]; then
    # We are on the server; append domain using the dedicated subcommand (safer than rewriting the full list).
    if command -v "${SCRIPTS_DIR}/main.sh" > /dev/null 2>&1; then
      log "  Appending ${HOST} to Caddy edge-http domains (if needed)."
      "${SCRIPTS_DIR}/main.sh" dns --type edge-http --add-domains "${HOST}"
    else
      echo "  Run: sudo ./bin/netcup-kube dns --type edge-http --add-domains \"${HOST}\""
    fi
  else
    echo "  From your laptop:"
    echo "    bin/netcup-kube-remote run dns --show --type edge-http --format csv  # to see current list"
    echo "    bin/netcup-kube-remote run dns --type edge-http --add-domains \"${HOST}\""
  fi
fi

echo
echo "RedisInsight UI:"
if [[ -n "${HOST}" ]]; then
  echo "  URL: https://${HOST}/"
else
  echo "  Port-forward: kubectl port-forward -n ${NAMESPACE} svc/redisinsight 8001:80"
  echo "  Then open: http://localhost:8001"
fi
echo
echo "To connect to Redis instances in the cluster:"
echo "  - Host: redis-master.${NAMESPACE}.svc.cluster.local (or your Redis service name)"
echo "  - Port: 6379"
echo "  - Auth: Get password from: kubectl get secret -n ${NAMESPACE} redis -o jsonpath='{.data.redis-password}' | base64 -d"
